spring:
  jpa:
    show-sql: false
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        temp:
          use_jdbc_metadata_defaults: false
        dialect:
          org.hibernate.dialect.PostgreSQL9Dialect
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
      INDENT_OUTPUT: true
  liquibase:
    parameters:
      sequence.increment_by: 1
      sequence.start_value: 10000
      sequence.min_value: 0
      uri.sequence.value_start: 10
      uri.sequence.value_increment: 1
      uri.sequence.value.min: 10
      uri.sequence.value.max: 10000000
      audit.schema: audit
    enabled: true

  datasource:
    url: jdbc:postgresql://localhost:5432/swnat
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver


## App Properties
jwt:
  secret: mySecret
  expirationInMs: 5048000000
  authoritiesKey: scopes